SELECT 
    a.AUTHOR_ID, c.AUTHOR_NAME, a.CATEGORY,
    SUM(a.PRICE * b.TOTAL_SALES) AS TOTAL_SALES
FROM 
    BOOK a,
    (
        SELECT BOOK_ID, SUM(SALES) AS TOTAL_SALES
        FROM BOOK_SALES
        WHERE DATE_FORMAT(SALES_DATE, "%Y-%m") = "2022-01"
        GROUP BY BOOK_ID
    ) b,
    AUTHOR c
WHERE 
    a.BOOK_ID = b.BOOK_ID AND a.AUTHOR_ID = c.AUTHOR_ID
GROUP BY a.AUTHOR_ID, a.CATEGORY
ORDER BY a.AUTHOR_ID ASC, a.CATEGORY DESC;