WITH TOTAL_SALES(PRODUCT_ID, AMOUNT) AS (
    SELECT PRODUCT_ID, SUM(SALES_AMOUNT)
    FROM OFFLINE_SALE
    GROUP BY PRODUCT_ID
)
SELECT 
    a.PRODUCT_CODE, 
    (a.PRICE * b.AMOUNT) AS SALES
FROM 
    PRODUCT a INNER JOIN TOTAL_SALES b
    ON a.PRODUCT_ID = b.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE ASC;
    