SELECT 
    DATE_FORMAT(a.SALES_DATE, "%Y-%m-%d") AS SALES_DATE,
    a.PRODUCT_ID, a.USER_ID, a.SALES_AMOUNT
FROM
    (
        SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
        FROM ONLINE_SALE
        UNION ALL
        SELECT SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
        FROM OFFLINE_SALE
    ) a
WHERE DATE_FORMAT(a.SALES_DATE, "%Y-%m") = "2022-03"
ORDER BY a.SALES_DATE ASC, a.PRODUCT_ID ASC, a.USER_ID ASC;