WITH 
    AVAILABLE_CARS(CAR_ID, AVAILABLE) AS (
        SELECT 
            CAR_ID,
            SUM(IF("2022-11-30" < START_DATE OR END_DATE < "2022-11-01", 0, 1))
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        GROUP BY CAR_ID
    ),
    MONTH_FEES(CAR_ID, CAR_TYPE, FEE) AS (
        SELECT
            a.CAR_ID, a.CAR_TYPE,
            FLOOR((a.DAILY_FEE * 30) * (100 - b.DISCOUNT_RATE) / 100) AS FEE
        FROM CAR_RENTAL_COMPANY_CAR a, CAR_RENTAL_COMPANY_DISCOUNT_PLAN b
        WHERE 
            a.CAR_TYPE = b.CAR_TYPE
            AND b.DURATION_TYPE = "30일 이상"
    )
SELECT a.CAR_ID, b.CAR_TYPE, b.FEE
FROM AVAILABLE_CARS a, MONTH_FEES b
WHERE 
    a.CAR_ID = b.CAR_ID
    AND b.CAR_TYPE IN ("세단", "SUV")
    AND 500000 <= b.FEE AND b.FEE < 2000000
    AND a.AVAILABLE = 0
ORDER BY b.FEE DESC, b.CAR_TYPE ASC, b.CAR_ID DESC;