SELECT 
    b.USER_ID, b.NICKNAME,
    CONCAT(b.CITY, " ", b.STREET_ADDRESS1, " ", b.STREET_ADDRESS2) AS "전체주소",
    CONCAT(SUBSTR(b.TLNO, 1, 3), "-", SUBSTR(b.TLNO, 4, 4), "-", SUBSTR(b.TLNO, 8, 4)) AS "전화번호"
FROM USED_GOODS_BOARD a, USED_GOODS_USER b
WHERE a.WRITER_ID = b.USER_ID
GROUP BY a.WRITER_ID
HAVING COUNT(*) >= 3
ORDER BY b.USER_ID DESC;