WITH 
    USER_INFO_YM(USER_ID, YEAR, MONTH) AS (
        SELECT USER_ID, YEAR(JOINED), MONTH(JOINED)
        FROM USER_INFO
        WHERE YEAR(JOINED) = 2021
    ),
    ONLINE_SALE_YM(USER_ID, YEAR, MONTH) AS (
        SELECT DISTINCT a.USER_ID, YEAR(a.SALES_DATE), MONTH(a.SALES_DATE)
        FROM ONLINE_SALE a, USER_INFO_YM b
        WHERE a.USER_ID = b.USER_ID
    )
SELECT 
    YEAR, MONTH,
    COUNT(USER_ID) AS PUCHASED_USERS,
    ROUND(COUNT(USER_ID) / (SELECT COUNT(*) FROM USER_INFO_YM), 1) AS PUCHASED_RATIO
FROM ONLINE_SALE_YM
GROUP BY YEAR, MONTH
ORDER BY YEAR ASC, MONTH ASC;