WITH HEAVY_USERS AS (
    SELECT HOST_ID
    FROM PLACES
    GROUP BY HOST_ID
    HAVING COUNT(*) >= 2
)
SELECT a.ID, a.NAME, a.HOST_ID
FROM PLACES a, HEAVY_USERS b
WHERE a.HOST_ID = b.HOST_ID
ORDER BY ID;