SELECT 
    a.PRODUCT_ID, b.PRODUCT_NAME,
    SUM(a.AMOUNT * b.PRICE) AS TOTAL_SALES
FROM FOOD_ORDER a, FOOD_PRODUCT b
WHERE 
    a.PRODUCT_ID = b.PRODUCT_ID
    AND DATE_FORMAT(a.PRODUCE_DATE, "%Y-%m") = "2022-05"
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, a.PRODUCT_ID ASC;