WITH 
    TRUCK_RENTAL_DURATIONS (HISTORY_ID, DAILY_FEE, DURATION) AS (
        SELECT 
            a.HISTORY_ID, b.DAILY_FEE,
            DATEDIFF(a.END_DATE, a.START_DATE) + 1
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY a, CAR_RENTAL_COMPANY_CAR b
        WHERE
            a.CAR_ID = b.CAR_ID
            AND b.CAR_TYPE = "트럭"
    ),
    TRUCK_RENTAL_PLANS (HISTORY_ID, DAILY_FEE, DURATION, DURATION_TYPE) AS (
        SELECT
            HISTORY_ID, DAILY_FEE, DURATION,
            CASE
                WHEN DURATION < 7 THEN NULL
                WHEN DURATION < 30 THEN "7일 이상"
                WHEN DURATION < 90 THEN "30일 이상"
                ELSE "90일 이상"
            END
        FROM TRUCK_RENTAL_DURATIONS
    )
SELECT 
    a.HISTORY_ID,
    FLOOR(a.DAILY_FEE * a.DURATION * (100 - IFNULL(b.DISCOUNT_RATE, 0)) / 100) AS FEE
FROM 
    TRUCK_RENTAL_PLANS a
    LEFT JOIN
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN b
    ON b.CAR_TYPE = "트럭" AND a.DURATION_TYPE = b.DURATION_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC;
