SELECT a.APNT_NO, b.PT_NAME, a.PT_NO, a.MCDP_CD, c.DR_NAME, a.APNT_YMD
FROM APPOINTMENT a, PATIENT b, DOCTOR c
WHERE
    a.PT_NO = b.PT_NO AND a.MDDR_ID = c.DR_ID
    AND a.MCDP_CD = "CS"
    AND DATE_FORMAT(a.APNT_YMD, "%Y-%m-%d") = "2022-04-13"
    AND a.APNT_CNCL_YN <> "Y"
ORDER BY a.APNT_YMD ASC;