WITH RECURSIVE TIME_TABLE(HOUR) AS (
    SELECT 0
    UNION ALL
    SELECT HOUR + 1 FROM TIME_TABLE WHERE HOUR < 23
)
SELECT a.HOUR AS "HOUR", COUNT(b.ANIMAL_ID) AS "COUNT"
FROM TIME_TABLE a LEFT JOIN ANIMAL_OUTS b ON a.HOUR = HOUR(b.DATETIME)
GROUP BY a.HOUR
ORDER BY a.HOUR ASC;