WITH TIME_TABLE AS (
    SELECT HOUR(DATETIME) AS OUT_HOUR
    FROM ANIMAL_OUTS
    WHERE HOUR(DATETIME) BETWEEN 9 AND 19
)
SELECT
    OUT_HOUR AS "HOUR", COUNT(*) AS "COUNT"
FROM TIME_TABLE
GROUP BY OUT_HOUR
ORDER BY OUT_HOUR ASC;