WITH REVIEW_COUNT(MEMBER_ID, TOTAL_REVIEWS) AS (
    SELECT MEMBER_ID, COUNT(*)
    FROM REST_REVIEW
    WHERE MEMBER_ID IS NOT NULL
    GROUP BY MEMBER_ID
)
SELECT 
    a.MEMBER_NAME, b.REVIEW_TEXT,
    DATE_FORMAT(b.REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM MEMBER_PROFILE a, REST_REVIEW b, REVIEW_COUNT c
WHERE 
    a.MEMBER_ID = b.MEMBER_ID
    AND a.MEMBER_ID = c.MEMBER_ID
    AND c.TOTAL_REVIEWS = (SELECT MAX(d.TOTAL_REVIEWS) FROM REVIEW_COUNT d)
ORDER BY b.REVIEW_DATE ASC, b.REVIEW_TEXT ASC;
