WITH RECORD(MONTH, CAR_ID) AS
(   SELECT MONTH(START_DATE) AS MONTH, CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE DATE_FORMAT(START_DATE, "%Y-%m") BETWEEN "2022-08" AND "2022-10"
)
SELECT 
    a.MONTH, a.CAR_ID,
    COUNT(*) AS RECORDS
FROM RECORD a
WHERE (SELECT COUNT(*) FROM RECORD b WHERE b.CAR_ID = a.CAR_ID) >= 5
GROUP BY a.MONTH, a.CAR_ID
ORDER BY a.MONTH ASC, a.CAR_ID DESC;