WITH CATEROTY_TABLE(PRODUCT_ID, CATEGORY) AS (
    SELECT PRODUCT_ID, SUBSTR(PRODUCT_CODE, 1, 2)
    FROM PRODUCT
)
SELECT CATEGORY, COUNT(*) AS PRODUCTS
FROM CATEROTY_TABLE
GROUP BY CATEGORY
ORDER BY CATEGORY ASC;