SELECT DISTINCT a.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY a, CAR_RENTAL_COMPANY_CAR b
WHERE 
    a.CAR_ID = b.CAR_ID
    AND b.CAR_TYPE = "세단"
    AND MONTH(a.START_DATE) = 10
ORDER BY a.CAR_ID DESC;