SELECT 
    CONCAT("/home/grep/src/", b.BOARD_ID, "/", b.FILE_ID, b.FILE_NAME, b.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_BOARD a, USED_GOODS_FILE b
WHERE
    a.BOARD_ID = b.BOARD_ID
    AND a.VIEWS = (SELECT MAX(c.VIEWS) FROM USED_GOODS_BOARD c)
ORDER BY b.FILE_ID DESC;