SELECT 
    a.CATEGORY,
    SUM(b.TOTAL_SALES) AS TOTAL_SALES
FROM 
    BOOK a,
    (
        SELECT BOOK_ID, SUM(SALES) AS TOTAL_SALES
        FROM BOOK_SALES
        WHERE DATE_FORMAT(SALES_DATE, "%Y-%m") = "2022-01"
        GROUP BY BOOK_ID
    ) b
WHERE a.BOOK_ID = b.BOOK_ID
GROUP BY a.CATEGORY
ORDER BY a.CATEGORY ASC;